### PR TITLE
GUVNOR-2861: Example import: Add jBPM example (evaluation project)

### PR DESCRIPTION
**Pull request by mcimbora**

### CODE REVIEW

**Comment by ge0ffrey** [comment]
Looks good for me, but added Kris xor Maciej to review and to merge as it's jbpm.

**Comment by mswiderski** [comment]
just one comment - it does use old form modeler forms (.form) instead of the new one (.frm) which might be good to use instead. @pefernan do we have anywhere the updated evaluation project that uses new forms?

Other than that looks good to me. I'll leave the final word to @krisv to double check if that is what he had in mind

**Comment by pefernan** [comment]
@mswiderski we don't have an updated version of this project, but I can migrate it if everyone agrees.

**Comment by mswiderski** [comment]
@pefernan thanks, we can do it once this is merged to not hold it back

**Comment by mcimbora** [comment]
@mswiderski @pefernan Sounds like a good plan, thanks for checking this.

**Comment by pefernan** [comment]
@mswiderski @mcimbora +1

**Comment by krisv** [comment]
+1, we should indeed plan to move to the new forms later though @pefernan

**Pull request merged**
